application: aqua-monitor
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /static/
  static_dir: static
- url: /oauth2callback
  script: oauth2client.appengine.application
- url: /.*
  script: server.app

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: pycrypto
  version: "2.6"
